[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['seaport-types/=lib/seaport-types/', '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
